# UR5 Drawing Configuration File
# This file contains all the configuration parameters for the UR5 drawing system

network:
  robot_ip: "192.168.1.102"
  pc_ip: "192.168.1.101"
  ur_type: "ur5"

physical:
  # Origin pose: [x, y, z, roll, pitch, yaw] - This is a Cartesian pose, not joint angles
  origin: [0.345, 0.517, 0.032, -1.26, 2.928, 0]
  paper_width: 0.2794   # 11 inches in meters
  paper_height: 0.2159  # 8.5 inches in meters
  lift_offset: 0.02     # Pen lift height in meters (0.2m in URScript becomes 0.02m here)
  drawing_speed: 0.25   # Drawing speed in m/s
  # Starting position - use origin pose as starting position
  start_position_pose: [-0.345, -0.517, 0.032, 1.26, -2.928, 0]  # Same as origin

image:
  width: 800
  height: 600

planning:
  planning_group: "ur_manipulator"  # UR robots use "ur_manipulator" not "manipulator"
  max_planning_attempts: 5
  planning_time: 5.0
  replan_attempts: 3
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.01

cartesian:
  eef_step: 0.005
  jump_threshold: 0.0
  avoid_collisions: true

safety:
  max_velocity: 0.5
  max_acceleration: 1.0
  # Additional UR-specific safety parameters
  speed_scaling: 0.25  # 25% of maximum speed for precise drawing
  safety_limits: true
  
# UR-specific controller parameters
controller:
  scaled_joint_trajectory_controller:
    speed_scaling_interface_name: "speed_scaling/speed_scaling_factor"
    goal_time_tolerance: 0.5
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.6

collision:
  object_padding: 0.01

files:
  drawing_sequences: "image_description.json"
  rviz_config: "drawing.rviz"
  calibration_file: "calibration.yaml"

launch:
  use_fake_hardware: false
  headless_mode: true
  initial_joint_controller: "scaled_joint_trajectory_controller"
  default_use_rviz: true
  default_use_sim_time: false

# UR robot specific configuration
ur_config:
  # Ensure model name consistency
  robot_name: "ur5"
  description_name: "robot_description"